/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExamSlugRouteImport } from './routes/exam.$slug'
import { Route as ApiPublicCronDispatchNotificationsRouteImport } from './routes/api/public/cron/dispatch-notifications'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamSlugRoute = ExamSlugRouteImport.update({
  id: '/exam/$slug',
  path: '/exam/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronDispatchNotificationsRoute =
  ApiPublicCronDispatchNotificationsRouteImport.update({
    id: '/api/public/cron/dispatch-notifications',
    path: '/api/public/cron/dispatch-notifications',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/exam/$slug': typeof ExamSlugRoute
  '/api/public/cron/dispatch-notifications': typeof ApiPublicCronDispatchNotificationsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/exam/$slug': typeof ExamSlugRoute
  '/api/public/cron/dispatch-notifications': typeof ApiPublicCronDispatchNotificationsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/exam/$slug': typeof ExamSlugRoute
  '/api/public/cron/dispatch-notifications': typeof ApiPublicCronDispatchNotificationsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/exam/$slug' | '/api/public/cron/dispatch-notifications'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/exam/$slug' | '/api/public/cron/dispatch-notifications'
  id:
    '__root__' | '/' | '/exam/$slug' | '/api/public/cron/dispatch-notifications'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExamSlugRoute: typeof ExamSlugRoute
  ApiPublicCronDispatchNotificationsRoute: typeof ApiPublicCronDispatchNotificationsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam/$slug': {
      id: '/exam/$slug'
      path: '/exam/$slug'
      fullPath: '/exam/$slug'
      preLoaderRoute: typeof ExamSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/dispatch-notifications': {
      id: '/api/public/cron/dispatch-notifications'
      path: '/api/public/cron/dispatch-notifications'
      fullPath: '/api/public/cron/dispatch-notifications'
      preLoaderRoute: typeof ApiPublicCronDispatchNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExamSlugRoute: ExamSlugRoute,
  ApiPublicCronDispatchNotificationsRoute:
    ApiPublicCronDispatchNotificationsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
