create table if not exists public.government_exams (
  id bigint generated by default as identity primary key,
  slug text unique not null,
  code text not null,
  name text not null,
  conducting_body text not null,
  category text not null,
  state text not null,
  application_deadline timestamptz not null,
  exam_date timestamptz not null,
  mode text not null check (mode in ('Online', 'Offline')),
  eligibility text not null,
  official_url text not null,
  tags text[] not null default '{}',
  is_tentative boolean not null default true,
  source_url text,
  verified_at timestamptz,
  updated_at timestamptz not null default now()
);

create index if not exists government_exams_category_idx
  on public.government_exams (category);
create index if not exists government_exams_state_idx
  on public.government_exams (state);
create index if not exists government_exams_deadline_idx
  on public.government_exams (application_deadline);

alter table public.government_exams enable row level security;

drop policy if exists "Public can read government exams" on public.government_exams;
create policy "Public can read government exams"
  on public.government_exams for select
  to anon, authenticated
  using (true);

revoke insert, update, delete on table public.government_exams from anon, authenticated;

insert into public.government_exams
  (slug, code, name, conducting_body, category, state, application_deadline, exam_date, mode, eligibility, official_url, tags)
values
  ('upsc-cse', 'UPSC CSE', 'Civil Services Examination', 'Union Public Service Commission', 'civil-services', 'All India', '2027-02-24T23:59:00+05:30', '2027-05-30T09:00:00+05:30', 'Offline', 'Graduate degree; age 21–32 years', 'https://upsc.gov.in', array['IAS','IPS','IFS']),
  ('upsc-cds', 'UPSC CDS', 'Combined Defence Services Examination', 'Union Public Service Commission', 'police-defense', 'All India', '2027-01-10T23:59:00+05:30', '2027-04-11T09:00:00+05:30', 'Offline', 'Graduate degree; unmarried candidates', 'https://upsc.gov.in', array['Army','Navy','Air Force']),
  ('upsc-capf', 'UPSC CAPF', 'Central Armed Police Forces (AC) Examination', 'Union Public Service Commission', 'police-defense', 'All India', '2027-03-16T23:59:00+05:30', '2027-08-01T09:00:00+05:30', 'Offline', 'Graduate degree; age 20–25 years', 'https://upsc.gov.in', array['BSF','CRPF','CISF']),
  ('ssc-cgl', 'SSC CGL', 'Combined Graduate Level Examination', 'Staff Selection Commission', 'staff-selection', 'All India', '2027-06-30T23:59:00+05:30', '2027-08-15T09:00:00+05:30', 'Online', 'Graduate degree; age varies by post', 'https://ssc.gov.in', array['Income Tax','Auditor','Assistant']),
  ('ssc-chsl', 'SSC CHSL', 'Combined Higher Secondary Level Examination', 'Staff Selection Commission', 'staff-selection', 'All India', '2027-05-07T23:59:00+05:30', '2027-07-01T09:00:00+05:30', 'Online', '12th pass; age 18–27 years', 'https://ssc.gov.in', array['LDC','DEO','Clerk']),
  ('ssc-gd', 'SSC GD', 'Constable (GD) in CAPFs Examination', 'Staff Selection Commission', 'police-defense', 'All India', '2027-12-20T23:59:00+05:30', '2027-02-05T09:00:00+05:30', 'Online', '10th pass; age 18–23 years', 'https://ssc.gov.in', array['Constable','CAPFs']),
  ('ibps-po', 'IBPS PO', 'Probationary Officer / Management Trainee', 'Institute of Banking Personnel Selection', 'banking', 'All India', '2027-07-28T23:59:00+05:30', '2027-09-20T09:00:00+05:30', 'Online', 'Graduate degree in any discipline', 'https://ibps.in', array['Bank PO','Officer']),
  ('sbi-po', 'SBI PO', 'State Bank of India Probationary Officer', 'State Bank of India', 'banking', 'All India', '2027-02-15T23:59:00+05:30', '2027-03-08T09:00:00+05:30', 'Online', 'Graduate degree; age 21–30 years', 'https://sbi.co.in', array['Bank PO','SBI']),
  ('rrb-ntpc', 'RRB NTPC', 'Non-Technical Popular Categories', 'Railway Recruitment Boards', 'railways', 'All India', '2027-01-31T23:59:00+05:30', '2027-06-12T09:00:00+05:30', 'Online', '12th or graduate level, post dependent', 'https://indianrailways.gov.in', array['Railway','Clerk','Station Master']),
  ('rrb-group-d', 'RRB Group D', 'Level 1 Railway Recruitment', 'Railway Recruitment Boards', 'railways', 'All India', '2027-03-02T23:59:00+05:30', '2027-09-01T09:00:00+05:30', 'Online', '10th pass or ITI; age 18–33 years', 'https://indianrailways.gov.in', array['Track Maintainer','Pointsman']),
  ('ctet', 'CTET', 'Central Teacher Eligibility Test', 'Central Board of Secondary Education', 'teaching', 'All India', '2027-09-18T23:59:00+05:30', '2027-12-07T09:00:00+05:30', 'Online', 'D.El.Ed / B.Ed qualification as applicable', 'https://ctet.nic.in', array['Teacher','Paper I','Paper II']),
  ('ugc-net', 'UGC NET', 'National Eligibility Test', 'National Testing Agency', 'teaching', 'All India', '2027-04-20T23:59:00+05:30', '2027-06-25T09:00:00+05:30', 'Online', 'Master’s degree with required percentage', 'https://ugcnet.nta.nic.in', array['JRF','Assistant Professor']),
  ('mpsc-state-services', 'MPSC', 'State Services Examination', 'Maharashtra Public Service Commission', 'civil-services', 'Maharashtra', '2027-02-28T23:59:00+05:30', '2027-05-07T09:00:00+05:30', 'Offline', 'Graduate degree; Marathi language requirement', 'https://mpsc.gov.in', array['Deputy Collector','PSI']),
  ('uppsc-pcs', 'UPPSC PCS', 'Combined State / Upper Subordinate Services', 'Uttar Pradesh Public Service Commission', 'civil-services', 'Uttar Pradesh', '2027-03-22T23:59:00+05:30', '2027-06-18T09:00:00+05:30', 'Offline', 'Graduate degree; post-specific qualifications', 'https://uppsc.up.nic.in', array['PCS','SDM'])
on conflict (slug) do nothing;
