create table if not exists public.exam_revisions (
  id bigint generated by default as identity primary key,
  exam_slug text not null,
  year integer not null check (year between 2024 and 2040),
  event_type text not null,
  label text,
  start_datetime timestamptz,
  end_datetime timestamptz,
  is_tentative boolean not null default true,
  is_extended boolean not null default false,
  removed boolean not null default false,
  revised_at timestamptz not null default now(),
  source_url text,
  note text
);

create index if not exists exam_revisions_year_revised_at_idx
  on public.exam_revisions (year, revised_at);

alter table public.exam_revisions enable row level security;

revoke all on table public.exam_revisions from anon, authenticated;
